name: Build macOS Application

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka pillow wand numpy requests

    - name: Run Nuitka to build the application
      run: |
        nuitka --standalone --assume-yes-for-downloads --deployment \
        --follow-imports --enable-plugin=tk-inter --clang \
        --include-data-dir=assets=assets \
        --include-data-files='license/LICENSE.txt=LICENSE.txt' \
        --macos-app-name="TextureAtlas to GIF and Frames" \
        --macos-app-icon=assets/icon.icns \
        --company-name="AutisticLulu" \
        --product-name="TextureAtlas to GIF and Frames" \
        --file-version=1.8.1 \
        --product-version=1.8.1 \
        --copyright="Copyright © 2024 AutisticLulu. Licensed under the GNU Affero General Public License (AGPL)" \
        --file-description="TextureAtlas to GIF and Frames" \
        "TextureAtlas to GIF and Frames.py"

    - name: Archive build output
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: ./TextureAtlas\ to\ GIF\ and\ Frames.dist/
